### ISSUE TITLE
Running repolinter fails due to missing is-windows module

### ISSUE THREAD

**Issue by benjaminSchilling33** [todogroup/repolinter#163]
## Issue Report

When running repolinter either stand-alone or with the docker container I get the follwoing error:

Docker:
```
Target directory: /app
Ruleset: rulesets/default.json
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'is-windows'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/lib/linguist.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Stand-alone (Debian 10):
```
npx repolinter
Target directory: /<target directory>
Ruleset: ../../../../usr/lib/node_modules/repolinter/rulesets/default.json
Cannot find module 'is-windows'
Require stack:
- /usr/lib/node_modules/repolinter/lib/linguist.js
- /usr/lib/node_modules/repolinter/axioms/linguist.js
- /usr/lib/node_modules/repolinter/index.js
- /usr/lib/node_modules/repolinter/bin/repolinter.js
```

Stand-alone (Windows 10)
```
npx repolinter
npx: installed 36 in 3.479s
Target directory: <target directory>
Ruleset: <path to rulesets>\rulesets\default.json
Cannot find module 'is-windows'
```

## Expected Behavior

I see the output as described in the README.md

## Actual Behavior
See above.

## Steps to Reproduce the Issue

Follow the steps described in the README.md

Tested with:
Docker
Debian 10, npm 6.14.4
Windows 10, npm 6.9.0

**Comment by mbwhite** [comment]
I can confirm that this is also an issue on Ubuntu 20LTS with both node 12 and node 10

**Comment by mbwhite** [comment]
As far as I can see, https://github.com/todogroup/repolinter/commit/3f48415c2eb26c2e46e6b4a5cfe8ced347abdc54 added the 'is-windows' lookup, but the module is not part of the normal dependencies. 

If you clone the repo, and use a full install (include devDependencies) is-windows is installed via some of the dev tools (eg nyc).

**Comment by benjaminSchilling33** [comment]
@mbwhite #164 fixed the issue for me, thanks a lot!
