### ISSUE TITLE
Running docker container doesn't find default ruleset

### ISSUE THREAD

**Issue by craigez** [todogroup/repolinter#167]
When trying to run the container on a directory repolinter looks for the path of the default ruleset in an odd location that is invalid within the container: 

[craign-mac:~/git/repolinter] craign% docker run 35f4d6fa63b9 ~/repolinter-working/repolinter/
Target directory: /Users/craign/repolinter-working/repolinter
Ruleset: ../../../../app/rulesets/default.json
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Linguist.identifyLanguagesSync (/app/lib/linguist.js:19:21)
    at module.exports (/app/axioms/linguist.js:8:28)
    at Object.getOwnPropertyNames.forEach.axiomId (/app/index.js:44:32)
    at Array.forEach (<anonymous>)
    at Object.lint (/app/index.js:38:48)
    at Object.<anonymous> (/app/bin/repolinter.js:21:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by trevmex** [comment]
Good find!

**Comment by prototypicalpro** [comment]
It looks like this was resolved at some point, not sure when. The docker image appears to work fine now.
